# experiments_config.yaml
experiments:
  - name: bert-base-uncased
    bert_model: 'bert-base-uncased'
    batch_size: 32
    learning_rate: 0.00005
    max_len: 128
    clip: 1.0
    patience: 3
    epochs: 50
    train: true
    data_dir: '../dataset/ATIS'

