# experiments_config.yaml
experiments:
  - name: lstm_sgd
    model: LSTM
    optimizer: SGD
    use_dropout: false
    dropout: 0.0
    learning_rate: 0.5
    hidden_dim: 256
    embedding_dim: 256
    batch_size: 64


  - name: lstm_sgd_dropout
    model: LSTM
    optimizer: SGD
    use_dropout: true
    dropout: 0.3
    learning_rate: 0.5
    hidden_dim: 512
    embedding_dim: 512
    batch_size: 64


  - name: lstm_adamw_dropout
    model: LSTM
    optimizer: AdamW
    use_dropout: true
    dropout: 0.6
    learning_rate: 0.001
    hidden_dim: 1024
    embedding_dim: 1024
    batch_size: 512
